require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResearchesController do

  # This should return the minimal set of attributes required to create a valid
  # Research. As you add validations to Research, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "lvl" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResearchesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all researches as @researches" do
      research = Research.create! valid_attributes
      get :index, {}, valid_session
      assigns(:researches).should eq([research])
    end
  end

  describe "GET show" do
    it "assigns the requested research as @research" do
      research = Research.create! valid_attributes
      get :show, {:id => research.to_param}, valid_session
      assigns(:research).should eq(research)
    end
  end

  describe "GET new" do
    it "assigns a new research as @research" do
      get :new, {}, valid_session
      assigns(:research).should be_a_new(Research)
    end
  end

  describe "GET edit" do
    it "assigns the requested research as @research" do
      research = Research.create! valid_attributes
      get :edit, {:id => research.to_param}, valid_session
      assigns(:research).should eq(research)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Research" do
        expect {
          post :create, {:research => valid_attributes}, valid_session
        }.to change(Research, :count).by(1)
      end

      it "assigns a newly created research as @research" do
        post :create, {:research => valid_attributes}, valid_session
        assigns(:research).should be_a(Research)
        assigns(:research).should be_persisted
      end

      it "redirects to the created research" do
        post :create, {:research => valid_attributes}, valid_session
        response.should redirect_to(Research.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved research as @research" do
        # Trigger the behavior that occurs when invalid params are submitted
        Research.any_instance.stub(:save).and_return(false)
        post :create, {:research => { "lvl" => "invalid value" }}, valid_session
        assigns(:research).should be_a_new(Research)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Research.any_instance.stub(:save).and_return(false)
        post :create, {:research => { "lvl" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested research" do
        research = Research.create! valid_attributes
        # Assuming there are no other researches in the database, this
        # specifies that the Research created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Research.any_instance.should_receive(:update_attributes).with({ "lvl" => "1" })
        put :update, {:id => research.to_param, :research => { "lvl" => "1" }}, valid_session
      end

      it "assigns the requested research as @research" do
        research = Research.create! valid_attributes
        put :update, {:id => research.to_param, :research => valid_attributes}, valid_session
        assigns(:research).should eq(research)
      end

      it "redirects to the research" do
        research = Research.create! valid_attributes
        put :update, {:id => research.to_param, :research => valid_attributes}, valid_session
        response.should redirect_to(research)
      end
    end

    describe "with invalid params" do
      it "assigns the research as @research" do
        research = Research.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Research.any_instance.stub(:save).and_return(false)
        put :update, {:id => research.to_param, :research => { "lvl" => "invalid value" }}, valid_session
        assigns(:research).should eq(research)
      end

      it "re-renders the 'edit' template" do
        research = Research.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Research.any_instance.stub(:save).and_return(false)
        put :update, {:id => research.to_param, :research => { "lvl" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested research" do
      research = Research.create! valid_attributes
      expect {
        delete :destroy, {:id => research.to_param}, valid_session
      }.to change(Research, :count).by(-1)
    end

    it "redirects to the researches list" do
      research = Research.create! valid_attributes
      delete :destroy, {:id => research.to_param}, valid_session
      response.should redirect_to(researches_url)
    end
  end

end
